### ISSUE TITLE
guidata broken by qtpy 2.0.0

### ISSUE THREAD

**Issue by cpascual** [conda-forge/guidata-feedstock#11]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

installation of guidata from conda-forge is broken since qtpy was upgraded to v2.0.0 

To reproduce : 

```console
$ conda create -n guidata guidata
(...)
$ conda activate guidata
(...)
$ python -c "import guidata; print('OK')" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cpascual/miniconda3/envs/guidata/lib/python3.10/site-packages/guidata/__init__.py", line 541, in <module>
    import guidata.config
  File "/home/cpascual/miniconda3/envs/guidata/lib/python3.10/site-packages/guidata/config.py", line 15, in <module>
    from guidata.configtools import add_image_module_path, get_translation
  File "/home/cpascual/miniconda3/envs/guidata/lib/python3.10/site-packages/guidata/configtools.py", line 22, in <module>
    from guidata.utils import get_module_path, decode_fs_string
  File "/home/cpascual/miniconda3/envs/guidata/lib/python3.10/site-packages/guidata/utils.py", line 28, in <module>
    from qtpy.py3compat import (
ModuleNotFoundError: No module named 'qtpy.py3compat'
$ conda install qtpy=1.11.3
(...)
$ python -c "import guidata; print('OK')" 
OK
```

<br/>
Environment (<code>$ conda list</code> ):
<details>

```
$ conda list
# packages in environment at /home/cpascual/miniconda3/envs/guidata:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
expat                     2.4.3                h9c3ff4c_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.94              ha180cfb_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gst-plugins-base          1.18.5               hf529b03_3    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
guidata                   1.7.9              pyh9f0ad1d_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libclang                  13.0.0          default_hc23dcda_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libglib                   2.70.2               h174f98d_1    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libllvm13                 13.0.0               hf817b99_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.1                 hd57d9b9_1    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mysql-common              8.0.28               ha770c72_0    conda-forge
mysql-libs                8.0.28               hfa10184_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.74                 hb5efdd6_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3          py310hff52083_8    conda-forge
pyqt-impl                 5.12.3          py310h1f8e252_8    conda-forge
pyqt5-sip                 4.19.18         py310h122e73d_8    conda-forge
pyqtchart                 5.12            py310hfcd6d55_8    conda-forge
pyqtwebengine             5.12.1          py310hfcd6d55_8    conda-forge
python                    3.10.2          h62f1059_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
qt                        5.12.9               ha98a1a1_5    conda-forge
qtpy                      2.0.0              pyhd8ed1ab_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                60.5.0          py310hff52083_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : guidata
    active env location : /home/cpascual/miniconda3/envs/guidata
            shell level : 1
       user config file : /home/cpascual/.condarc
 populated config files : /home/cpascual/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.10.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/cpascual/miniconda3  (writable)
      conda av data dir : /home/cpascual/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/cpascual/miniconda3/pkgs
                          /home/cpascual/.conda/pkgs
       envs directories : /home/cpascual/miniconda3/envs
                          /home/cpascual/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.5 Linux/5.10.0-10-amd64 debian/11 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by cpascual** [comment]
This is already [fixed in guidata v2](https://github.com/PierreRaybaut/guidata/issues/52#issuecomment-1001507299)

So, probably the best would be to fix the issues currently blocking guidata 2.0.2 from being packaged in conda.

... but, if that is not easy, maybe a workaround consisting of pinning the qtpy dependency to to 1.11.3 in guidata v1.7.9  should be considered.
